// src/api/jobs.ts
import { supabase } from '../lib/supabase';
import { buildJobPaymentBreakdown } from '../utils/jobPayments';

// ---------- Helpers ----------
function toInt(x: any, label = 'number') {
  const n = Number(x);
  if (!Number.isFinite(n)) throw new Error(`Invalid ${label}: ${x}`);
  return Math.round(n);
}



export async function setClientFinalRequestSent(jobId: string) {
  const { error } = await supabase
    .from('jobs')
    .update({ client_final_request_sent: true })
    .eq('id', jobId);
  if (error) throw error;
}

// ---------- Actions ----------
/** Client accepts job → creates a payments row and sets status=accepted */
export async function acceptJob(jobId: string) {
  const { data: job, error: e1 } = await supabase
    .from('jobs')
    // This stays compatible while the optional payment columns roll out.
    .select('*')
    .eq('id', jobId)
    .single();
  if (e1) throw e1;

  const { data: items, error: itemsError } = await supabase
    .from('job_items')
    .select('qty, price_cents')
    .eq('job_id', jobId);
  if (itemsError) throw itemsError;

  const breakdown = buildJobPaymentBreakdown(job as any, items || []);
  const principal = toInt(breakdown.tradieGrossCents, 'principal');
  if (principal <= 0) throw new Error('Job price must be > 0');

  const client_fee = toInt(breakdown.clientFeeCents, 'client_fee');
  const seller_fee = toInt(breakdown.sellerFeeCents, 'seller_fee');
  const total = toInt(breakdown.totalDueCents, 'total');
  const net_to_seller = toInt(breakdown.netToSellerCents, 'net_to_seller');

  const { data: { user } } = await supabase.auth.getUser();
  if (!user) throw new Error('Not signed in');
  if (job.client_id !== user.id) throw new Error('Only the customer can approve this job.');
  if (!['proposed', 'accepted'].includes(job.status)) {
    throw new Error('This job is not ready for approval.');
  }

  // Payment rows are created by the authenticated checkout function. Approval
  // only changes job state, so it is safe when a user taps more than once.
  if (job.status === 'proposed') {
    const { error: e3 } = await supabase
      .from('jobs')
      .update({ status: 'accepted' })
      .eq('id', job.id)
      .eq('status', 'proposed');
    if (e3) throw e3;
  }

  return { principal, client_fee, seller_fee, total, net_to_seller };
}



export async function resendProposal(jobId: string, fields: {
  title?: string;
  description?: string;
  price_cents?: number;
  duration_days?: number;
}) {
  const payload: any = { ...fields, status: 'proposed' };
  const { error } = await supabase.from('jobs').update(payload).eq('id', jobId);
  if (error) throw error;
}

export async function createJobWithDates(payload: {
  title: string;
  description?: string;
  price_cents: number;
  start_date: string; // 'YYYY-MM-DD'
  end_date: string;   // 'YYYY-MM-DD'
}) {
  const { data: { user } } = await supabase.auth.getUser();
  if (!user) throw new Error('Not authenticated');

  const { data, error } = await supabase
    .from('jobs')
    .insert({
      trader_id: user.id,
      title: payload.title,
      description: payload.description ?? null,
      price_cents: payload.price_cents,
      start_date: payload.start_date,
      end_date: payload.end_date,
      currency: 'GBP',
      ref_code: null, // generated by trigger if you have one
    })
    .select()
    .single();

  if (error) throw error;
  return data;
}


export async function declineJobWithReason(jobId: string, reason: string) {
  const { data: { user } } = await supabase.auth.getUser();
  if (!user) throw new Error('Not authenticated');

  const body = `Denied: ${reason?.trim() || '(no reason provided)'}`;
  await supabase.from('messages').insert({
    job_id: jobId,
    sender_id: user.id,
    body,
  });

  // Update without returning representation (avoids 400 even if RLS blocks select)
  const { error: updErr } = await supabase
    .from('jobs')
    .update({ status: 'cancelled', decline_reason: reason?.trim() || null })
    .eq('id', jobId);
  if (updErr) throw updErr;

  // (optional) return nothing; caller just reloads jobs
  return;
}

/** Client declines job with a reason (stores an offer + reverts to proposed) */
export async function declineJob(jobId: string, reason: string) {
  if (!reason || !reason.trim()) throw new Error('Please enter a reason.');
  const { data: job, error: ej } = await supabase
    .from('jobs')
    .select('price_cents, duration_days')
    .eq('id', jobId)
    .single();
  if (ej) throw ej;

  const { error: e1 } = await supabase.from('offers').insert({
    job_id: jobId,
    status: 'declined',
    decline_reason: reason.trim(),
    price_cents: job.price_cents,
    duration_days: job.duration_days,
  });
  if (e1) throw e1;

  const { error: e2 } = await supabase.from('jobs').update({ status: 'proposed' }).eq('id', jobId);
  if (e2) throw e2;
}

/** Trader marks job done → set auto_release_at = now()+7days */
export async function sellerMarksDone(jobId: string) {
  const { error } = await supabase.rpc('rpc_seller_marks_done', { p_job_id: jobId });
  if (error) throw error;
}



export async function markCompleted(jobId: string) {
  const { error } = await supabase.from('jobs').update({ status: 'completed' }).eq('id', jobId);
  if (error) throw error;
}
/** Client marks job complete → call payout edge function */
export async function clientMarksDone(jobId: string) {
  // if seller already done, set completed; otherwise set client_done (optional)
  const { data, error } = await supabase
    .from('jobs')
    .update({ status: 'client_done' })
    .eq('id', jobId)
    .select('status')
    .single();
  if (error) throw error;

  // Optionally: a SQL trigger could auto-advance to completed when both are done.
}

/** Client says not done → open dispute with note */
export async function clientNotDone(jobId: string, reason: string) {
  // 1) Mark as disputed (or keep your existing behavior)
  const { error } = await supabase.from('jobs').update({ status: 'disputed' }).eq('id', jobId);
  if (error) throw error;

  // 2) Email ops via Edge Function (create the function shown below)
  await supabase.functions.invoke('send-incomplete', {
    body: { jobId, reason },
  });
}
